### PR TITLE
Add docs and fix minor bug

### LINKED ISSUE #114: Add JSDoc for code explanation

### LINKED ISSUE #127: Fix numbers not appearing for buckets in bucket sort

### PR DESCRIPTION
**Pull request by keanecjy**
Fixes #127 
Fixes #114 

Add lazy loading to state variables

### CODE REVIEW

File: src/visualizer/codeinformation/codeexplaination/PerformanceSection.js [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+      <p>O({sortDetails.worstSpace})</p>
+    </div>
+  );
+
+  /**
+   * General type with icon template, used for detailing whether the sorting algorithm used is
+   * stable and in-place.
+   *
+   * @param {string} type Input type.
+   * @param boolean Boolean detailing whether the type is true or false.
```
Comment (seanjyjy) [inline src/visualizer/codeinformation/codeexplaination/PerformanceSection.js]: missing parenthesis

File: src/visualizer/codeinformation/codetemplate/Selector.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+ * @component
+ * @category CodeTemplate
+ * @returns {JSX.Element} Selector component.
+ */
+const Selector = ({ selected, setSelected }) => {
+  /**
+   * Select button for users to choose the programming language.
+   *
+   * @param language Programming language.
+   * @returns {JSX.Element} Select button.
```
Comment (seanjyjy) [inline src/visualizer/codeinformation/codetemplate/Selector.js:17]: Maybe could write it as @param language. Programming language.
That's what I did for most of my params, it makes it slightly more readable

File: src/visualizer/codeinformation/templates/radixSortTemplate.js [hunk 3]
```diff
@@ -1,3 +1,9 @@
+/**
+ * Radix sort algorithm details.
+ *
```
Comment (seanjyjy) [inline src/visualizer/codeinformation/templates/radixSortTemplate.js:3]: Is there a missing reference link?

File: src/visualizer/sortingvisualizer/util/RadixSortUtil.js [hunk 4]
```diff
@@ -1,6 +1,10 @@
 import { generateValue } from './GeneralUtil';
 
-// Fixed array for radix sort
+/**
+ * Fixed stack array created for radix and bucket sort usage.
+ *
+ * @type {Object} Stack array.
```
Comment (seanjyjy) [inline src/visualizer/sortingvisualizer/util/RadixSortUtil.js]: i think the type is {Object[]}?

File: src/visualizer/codeinformation/codeexplaination/CodeExplanation.js [hunk 5]
```diff
@@ -1,74 +1,54 @@
...
-        <p>θ({sort.averageTime})</p>
-        <p>Ω({sort.bestTime})</p>
-        <p>O({sort.worstSpace})</p>
-      </div>
-    );
+  /**
+   * First header component for the explanation section.
+   *
+   * @returns {JSX.Element} First header component for the explanation section.
+   */
```
Comment (seanjyjy) [inline src/visualizer/codeinformation/codeexplaination/CodeExplanation.js:27]: I am not sure if the returns statement value-add anything? it could be simplified as 
```
/**
  * First header component for the explanation section.
  */

File: src/visualizer/codeinformation/codeexplaination/PerformanceSection.js (hunk 1 above)
Comment (keanecjy) [reply src/visualizer/codeinformation/codeexplaination/PerformanceSection.js]: Ok will fix.

File: src/visualizer/sortingvisualizer/util/RadixSortUtil.js (hunk 4 above)
Comment (keanecjy) [reply src/visualizer/sortingvisualizer/util/RadixSortUtil.js]: Yup

File: src/visualizer/codeinformation/codeexplaination/CodeExplanation.js (hunk 5 above)
Comment (keanecjy) [reply src/visualizer/codeinformation/codeexplaination/CodeExplanation.js:27]: Does not seem to add much, but doing it to follow jsdoc style.

File: src/visualizer/codeinformation/templates/radixSortTemplate.js (hunk 3 above)
Comment (keanecjy) [reply src/visualizer/codeinformation/templates/radixSortTemplate.js:3]: Perhaps i lost the link for this algorithm, will try to find it and put it in.

**Comment by seanjyjy** [comment]
LGTM
