### PR TITLE
Improve code quality and fix quicksort algorithm to match its template

### LINKED ISSUE #94: Fix replay button not appearing
1. Counting sort
2. Radix sort
3. Merge sort

### LINKED ISSUE #95: Fix space issue in selection sort explanation

### LINKED ISSUE #97: Improve code quality in visualizer
* Abstract out functional logic in visualizer file
* Check and improve general code quality of all files

### LINKED ISSUE #98: Update quick sort code templates to match animation

### PR DESCRIPTION
**Pull request by seanjyjy**
**Pr Overview**
* Improve code quality
* Fix quicksort Algorithm to match its template
* Fix replay button not appearing when using the forward and backward button
* Fix space issue in selection sort explanation
* Fix typos in explanations

### CODE REVIEW

File: src/visualizer/sortingvisualizer/Visualizer.js [hunk 1]
```diff
@@ -136,30 +139,11 @@ const Visualizer = () => {
     } else if (isRadixSort(visualizerAlgorithm)) {
       executeRadixSort(currentAnimation, referenceArray, stackArr, false);
     } else if (isMergeSort(visualizerAlgorithm)) {
-      let nextReferenceArray = historyArr.pop();
-      setHistoryArr(historyArr);
-      setReferenceArray(nextReferenceArray);
+      executeMergeSortBackward(historyArr, setReferenceArray);
```
Comment (keanecjy) [inline src/visualizer/sortingvisualizer/Visualizer.js:142]: Just curious as to what is the difference between the forward and backward animation and why the former requires the nextReferenceArray and the latter does not?

**Review by keanecjy — APPROVED** [review]
LGTM
